[project]
name = "ai-game-playing"
version = "0.1.0"
description = "Using AI to play simple games."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
notebooks = [
    "ipykernel>=6.29.5",
]
